# Generated by Django 2.0.5 on 2019-09-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testproject', models.CharField(default='', max_length=50, verbose_name='测试项目')),
                ('testmodule', models.CharField(default='', max_length=50, verbose_name='项目模块')),
                ('reportname', models.CharField(default='', max_length=20, verbose_name='测试执行开始时间串')),
                ('reportfile', models.FileField(max_length=1000, upload_to='report/%Y%m', verbose_name='报告文件')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '报告记录',
                'verbose_name_plural': '报告记录',
            },
        ),
    ]
