# Generated by Django 2.0.5 on 2019-09-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickandback',
            name='is_click_same_check',
            field=models.BooleanField(default=True, verbose_name='要点击元素与标识元素是否一致'),
        ),
    ]
