# Generated by Django 2.0.5 on 2019-09-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0003_auto_20190902_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickandback',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='是否新窗口'),
        ),
    ]
