# Generated by Django 2.0.5 on 2019-09-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0004_clickandback_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickandback',
            name='current_page_check_ele_find',
            field=models.CharField(default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, verbose_name='当前页面标识元素查找风格'),
        ),
        migrations.AlterField(
            model_name='clickandback',
            name='current_page_click_ele_find',
            field=models.CharField(blank=True, default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, null=True, verbose_name='当前页面要点击元素查找风格'),
        ),
        migrations.AlterField(
            model_name='clickandback',
            name='next_page_check_ele_find',
            field=models.CharField(default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, verbose_name='下一页面标识元素查找风格'),
        ),
    ]
