# Generated by Django 2.0.5 on 2019-09-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0005_auto_20190902_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clickandback',
            name='current_page_check_ele_find',
        ),
        migrations.RemoveField(
            model_name='clickandback',
            name='current_page_check_ele_find_value',
        ),
        migrations.RemoveField(
            model_name='clickandback',
            name='is_click_same_check',
        ),
        migrations.AlterField(
            model_name='clickandback',
            name='current_page_click_ele_find',
            field=models.CharField(default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, verbose_name='当前页面要点击元素查找风格'),
        ),
        migrations.AlterField(
            model_name='clickandback',
            name='current_page_click_ele_find_value',
            field=models.CharField(default='', max_length=1000, verbose_name='当前页面要点击元素查找风格的确切值'),
        ),
    ]
