# Generated by Django 2.0.5 on 2019-09-13 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0007_newaddandcheck'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clickandback',
            options={'verbose_name': '点击场景', 'verbose_name_plural': '点击场景'},
        ),
    ]
