# Generated by Django 2.0.5 on 2019-09-13 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testdatas', '0008_auto_20190913_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='newaddandcheck',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='添加人'),
        ),
    ]
