# Generated by Django 2.0.5 on 2019-09-13 17:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0009_newaddandcheck_write_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputTapInputText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_ele_find', models.CharField(default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, verbose_name='确定按钮查找风格')),
                ('input_ele_find_value', models.CharField(default='', max_length=1000, verbose_name='确定按钮查找风格的确切值')),
                ('input_text', models.CharField(default='', max_length=300, verbose_name='输入框中输入的内容')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('newaddandcheck', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testdatas.NewAddAndCheck', verbose_name='依赖的添加场景')),
            ],
            options={
                'verbose_name': '新增场景',
                'verbose_name_plural': '新增场景',
            },
        ),
    ]
