# Generated by Django 2.0.5 on 2019-09-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0010_inputtapinputtext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inputtapinputtext',
            options={'verbose_name': '新增输入框及输入内容', 'verbose_name_plural': '新增输入框及输入内容'},
        ),
    ]
