# Generated by Django 2.0.5 on 2019-09-13 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0012_auto_20190913_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selecttapselectoption',
            options={'verbose_name': '新增选项框及选项内容', 'verbose_name_plural': '新增选项框及选项内容'},
        ),
    ]
